# Cloud Build configuration for frontend deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/options-desk-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/options-desk-frontend:latest'
      - '-f'
      - 'deployment/docker/frontend/Dockerfile'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/options-desk-frontend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/options-desk-frontend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'options-desk-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/options-desk-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/options-desk-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/options-desk-frontend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
